In [2]:
import torch.nn as nn
import torch.nn.init as init

def initialize_parameters(model, init_method='uniform', **kwargs):
    """
    Khởi tạo tham số cho mạng neural network.

    Args:
        model (nn.Module): Mô hình PyTorch cần khởi tạo.
        init_method (str): Phương pháp khởi tạo. Hỗ trợ: 'uniform', 'normal', 
                           'xavier_uniform', 'xavier_normal', 'kaiming_uniform', 'kaiming_normal'.
        **kwargs: Tham số bổ sung cho hàm khởi tạo (ví dụ: mean và std cho normal, a và b cho uniform).
    """
    
    def init_weight(m):
        if isinstance(m, nn.Linear) or isinstance(m, nn.Conv2d):
            if init_method == 'uniform':
                init.uniform_(m.weight, **kwargs)
            elif init_method == 'normal':
                init.normal_(m.weight, **kwargs)
            elif init_method == 'xavier_uniform':
                init.xavier_uniform_(m.weight, **kwargs)
            elif init_method == 'xavier_normal':
                init.xavier_normal_(m.weight, **kwargs)
            elif init_method == 'kaiming_uniform':
                init.kaiming_uniform_(m.weight, **kwargs)
            elif init_method == 'kaiming_normal':
                init.kaiming_normal_(m.weight, **kwargs)
            else:
                raise ValueError(f"Không hỗ trợ phương pháp khởi tạo: {init_method}")
            
            if m.bias is not None:
                init.constant_(m.bias, 0)

    model.apply(init_weight)

# Ví dụ sử dụng
class MyNetwork(nn.Module):
    def __init__(self):
        super(MyNetwork, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 50, 5)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

# Tạo một instance của MyNetwork
net = MyNetwork()
# Khởi tạo tham số sử dụng phương pháp 'kaiming_normal' cho ReLU activation
# initialize_parameters(net, init_method='kaiming_normal', nonlinearity='relu')
initialize_parameters(net, init_method='normal', mean=0, std=0.1)


In [1]:
import numpy as np

def create_Y_from_X(X):
    # Lấy các phần tử từng ô theo hàng và cột
    top_left = X[:-1, :-1]
    top_right = X[:-1, 1:]
    bottom_left = X[1:, :-1]
    bottom_right = X[1:, 1:]
    
    # Tính giá trị trung bình cộng của mỗi ô
    Y = (top_left + top_right + bottom_left + bottom_right) / 4
    
    return Y

# Ví dụ
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

Y = create_Y_from_X(X)
print(Y)


[[ 3.5  4.5  5.5]
 [ 7.5  8.5  9.5]
 [11.5 12.5 13.5]]


In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# Thêm phần dày b��ng giá trị 0
arr1 = np.pad(arr, ((1, 1), (1, 1)), mode='constant', constant_values=0)
print(arr1)

# Thêm phần dày b��ng giá trị cuối cùng của mảng
arr2 = np.pad(arr, ((1, 1), (1, 1)), mode='edge')
print(arr2)

[[1 2 3]
 [4 5 6]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]


In [8]:
import numpy as np

# Mảng numpy ban đầu
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape với chiều hoặc trục khác nhau
reshaped_arr = np.reshape(arr, (2, 2, 2), order='F')  # Sắp xếp theo cột

print("Mảng ban đầu:")
print(arr)
print("\nMảng sau khi reshape với chiều hoặc trục khác nhau:")
print(reshaped_arr)
print(reshaped_arr.flatten(order='F'))


Mảng ban đầu:
[1 2 3 4 5 6 7 8]

Mảng sau khi reshape với chiều hoặc trục khác nhau:
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
[1 2 3 4 5 6 7 8]


In [6]:
import numpy as np

# Mảng numpy ban đầu
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape với chiều hoặc trục khác nhau
reshaped_arr = np.reshape(arr, (2, 2, 2), order='C')  # Sắp xếp theo cột

print("Mảng ban đầu:")
print(arr)
print("\nMảng sau khi reshape với chiều hoặc trục khác nhau:")
print(reshaped_arr)


Mảng ban đầu:
[1 2 3 4 5 6 7 8]

Mảng sau khi reshape với chiều hoặc trục khác nhau:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
4%2

0

In [15]:
10000%11

1